### ISSUE TITLE
Het is beter om niet de database ID aan de gebruiker te tonen, deze hoeven niet opeenvolgend te zijn

### ISSUE THREAD

**Issue by JeroenHeemskerk** [vincentlemstra/educom-csharp-born2move#2]
In je code gebruik je de database id als nummer in de lijst met moves, dit is niet correct, database id's hoeven niet bij 1 te beginnen en zijn mogelijk ook niet opvolgend. Beter is het om database id's niet te tonen aan de gebruiker.
https://github.com/vincentlemstra/educom-csharp-born2move/blob/177cdf6e59f151b2c0d93e64afb9e84f05b30714/BornToMove/Program.cs#L68-L71

Ik zou de 'index' in de lijst + 1 gebruiken om te tonen, dus je laat een extra teller meelopen bij de foreach om het nummer te printen en dan neem je dat nummer - 1 als index om de move te selecteren

**Comment by vincentlemstra** [comment]
// show all moves
            var moves = new MoveBL().GetAllMoves();
            int i = 1;
            moves.ForEach(move =>
            {
                WriteLine($"Toets [{i}] {move.Name} | sweat rate: {move.SweatRate} ");
                i++;
            });
